<a href="https://colab.research.google.com/github/prachikushwaha007-ai/digital_humanities-history/blob/main/1_Practice_lib_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#1.3.2
import pandas as pd

In [ ]:
names_dict={"names" : ["Tom","Jerry","Rose","Jeff","Merry","James"]}
for name in names_dict:
   print (names)

['Tom', 'Jerry', 'Rose', 'Jeff', 'Merry', 'James']

In [ ]:
df=pd.DataFrame(names_dict)
df

   names
0    Tom
1  Jerry
2   Rose
3   Jeff
4  Merry
5  James

In [ ]:
print(df)

   names
0    Tom
1  Jerry
2   Rose
3   Jeff
4  Merry
5  James

In [ ]:
df.to_csv("sample_data/mnist_test.csv",index=False)
df2 = pd.read_csv("sample_data/mnist_test.csv")
df2

   names
0    Tom
1  Jerry
2   Rose
3   Jeff
4  Merry
5  James

In [ ]:
df2

   names
0    Tom
1  Jerry
2   Rose
3   Jeff
4  Merry
5  James

In [ ]:
df2.to_json("sample_data/mnist_test.json")

In [ ]:
df4 = pd.read_json("sample_data/mnist_test.json")

In [ ]:
df4

   names
0    Tom
1  Jerry
2   Rose
3   Jeff
4  Merry
5  James

In [ ]:
df4["ages"] = [20,21,25,29,31,56]

In [ ]:
df4

   names  ages
0    Tom    20
1  Jerry    21
2   Rose    25
3   Jeff    29
4  Merry    31
5  James    56

In [ ]:
#To grab a single column from data#
names=df4.names
names

0      Tom
1    Jerry
2     Rose
3     Jeff
4    Merry
5    James
Name: names, dtype: object

In [ ]:
ages=df4.ages
ages

0    20
1    21
2    25
3    29
4    31
5    56
Name: ages, dtype: int64

In [ ]:
#iloc
row1=df4.iloc[1]

In [ ]:
row1

names    Jerry
ages        21
Name: 1, dtype: object