<a href="https://colab.research.google.com/github/prachikushwaha007-ai/digital_humanities-history/blob/main/7_Regex_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.head(891)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
names = df.Name.tolist()
names

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'Moran, Mr. James',
 'McCarthy, Mr. Timothy J',
 'Palsson, Master. Gosta Leonard',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Nasser, Mrs. Nicholas (Adele Achem)',
 'Sandstrom, Miss. Marguerite Rut',
 'Bonnell, Miss. Elizabeth',
 'Saundercock, Mr. William Henry',
 'Andersson, Mr. Anders Johan',
 'Vestrom, Miss. Hulda Amanda Adolfina',
 'Hewlett, Mrs. (Mary D Kingcome) ',
 'Rice, Master. Eugene',
 'Williams, Mr. Charles Eugene',
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
 'Masselmani, Mrs. Fatima',
 'Fynney, Mr. Joseph J',
 'Beesley, Mr. Lawrence',
 'McGowan, Miss. Anna "Annie"',
 'Sloper, Mr. William Thompson',
 'Palsson, Miss. Torborg Danira',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Emir, Mr. Farred Chehab',
 'Fortune, Mr. Charles Alexander',
 'O\'Dwyer, Miss. Ellen "Nellie"',
 'Todoroff, Mr. Lalio',
 'Uruchurtu, Don. Manuel E',
 'Spencer, Mrs. William Augustus (Marie Eugenie)',
 'Glynn, Miss. Mary Agatha',
 'Wheadon, Mr. Edward H',
 'Meyer, Mr. Edgar Joseph',
 'Holverson, Mr. Alexander Oskar',
 'Mamee, Mr. Hanna',
 'Cann, Mr. Ernest Charles',
 'Vander Planke, Miss. Augusta Maria',
 'Nicola-Yarred, Miss. Jamila',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
 'Kraeff, Mr. Theodor',
 'Laroche, Miss. Simonne Marie Anne Andree',
 'Devaney, Miss. Margaret Delia',
 'Rogers, Mr. William John',
 'Lennon, Mr. Denis',
 "O'Driscoll, Miss. Bridget",
 'Samaan, Mr. Youssef',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Panula, Master. Juha Niilo',
 'Nosworthy, Mr. Richard Cater',
 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
 'Ostby, Mr. Engelhart Cornelius',
 'Woolner, Mr. Hugh',
 'Rugg, Miss. Emily',
 'Novel, Mr. Mansouer',
 'West, Miss. Constance Mirium',
 'Goodwin, Master. William Frederick',
 'Sirayanian, Mr. Orsen',
 'Icard, Miss. Amelie',
 'Harris, Mr. Henry Birkhardt',
 'Skoog, Master. Harald',
 'Stewart, Mr. Albert A',
 'Moubarek, Master. Gerios',
 'Nye, Mrs. (Elizabeth Ramell)',
 'Crease, Mr. Ernest James',
 'Andersson, Miss. Erna Alexandra',
 'Kink, Mr. Vincenz',
 'Jenkin, Mr. Stephen Curnow',
 'Goodwin, Miss. Lillian Amy',
 'Hood, Mr. Ambrose Jr',
 'Chronopoulos, Mr. Apostolos',
 'Bing, Mr. Lee',
 'Moen, Mr. Sigurd Hansen',
 'Staneff, Mr. Ivan',
 'Moutal, Mr. Rahamin Haim',
 'Caldwell, Master. Alden Gates',
 'Dowdell, Miss. Elizabeth',
 'Waelens, Mr. Achille',
 'Sheerlinck, Mr. Jan Baptist',
 'McDermott, Miss. Brigdet Delia',
 'Carrau, Mr. Francisco M',
 'Ilett, Miss. Bertha',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Ford, Mr. William Neal',
 'Slocovski, Mr. Selman Francis',
 'Fortune, Miss. Mabel Helen',
 'Celotti, Mr. Francesco',
 'Christmann, Mr. Emil',
 'Andreasson, Mr. Paul Edvin',
 'Chaffee, Mr. Herbert Fuller',
 'Dean, Mr. Bertram Frank',
 'Coxon, Mr. Daniel',
 'Shorney, Mr. Charles Joseph',
 'Goldschmidt, Mr. George B',
 'Greenfield, Mr. William Bertram',
 'Doling, Mrs. John T (Ada Julia Bone)',
 'Kantor, Mr. Sinai',
 'Petranec, Miss. Matilda',
 'Petroff, Mr. Pastcho ("Pentcho")',
 'White, Mr. Richard Frasar',
 'Johansson, Mr. Gustaf Joel',
 'Gustafsson, Mr. Anders Vilhelm',
 'Mionoff, Mr. Stoytcho',
 'Salkjelsvik, Miss. Anna Kristine',
 'Moss, Mr. Albert Johan',
 'Rekic, Mr. Tido',
 'Moran, Miss. Bertha',
 'Porter, Mr. Walter Chamberlain',
 'Zabour, Miss. Hileni',
 'Barton, Mr. David John',
 'Jussila, Miss. Katriina',
 'Attalah, Miss. Malake',
 'Pekoniemi, Mr. Edvard',
 'Connors, Mr. Patrick',
 'Turpin, Mr. William John Robert',
 'Baxter, Mr. Quigg Edmond',
 'Andersson, Miss. Ellis Anna Maria',
 'Hickman, Mr. Stanley George',
 'Moore, Mr. Leonard Charles',
 'Nasser, Mr. Nicholas',
 'Webber, Miss. Susan',
 'White, Mr. Percival Wayland',
 'Nicola-Yarred, Master. Elias',
 'McMahon, Mr. Martin',
 'Madsen, Mr. Fridtjof Arne',
 'Peter, Miss. Anna',
 'Ekstrom, Mr. Johan',
 'Drazenoic, Mr. Jozef',
 'Coelho, Mr. Domingos Fernandeo',
 'Robins, Mrs. Alexander A (Grace Charity Laury)',
 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
 'Sobey, Mr. Samuel James Hayden',
 'Richard, Mr. Emile',
 'Newsom, Miss. Helen Monypeny',
 'Futrelle, Mr. Jacques Heath',
 'Osen, Mr. Olaf Elon',
 'Giglio, Mr. Victor',
 'Boulos, Mrs. Joseph (Sultana)',
 'Nysten, Miss. Anna Sofia',
 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
 'Burke, Mr. Jeremiah',
 'Andrew, Mr. Edgardo Samuel',
 'Nicholls, Mr. Joseph Charles',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Ford, Miss. Robina Maggie "Ruby"',
 'Navratil, Mr. Michel ("Louis M Hoffman")',
 'Byles, Rev. Thomas Roussel Davids',
 'Bateman, Rev. Robert James',
 'Pears, Mrs. Thomas (Edith Wearne)',
 'Meo, Mr. Alfonzo',
 'van Billiard, Mr. Austin Blyler',
 'Olsen, Mr. Ole Martin',
 'Williams, Mr. Charles Duane',
 'Gilnagh, Miss. Katherine "Katie"',
 'Corn, Mr. Harry',
 'Smiljanic, Mr. Mile',
 'Sage, Master. Thomas Henry',
 'Cribb, Mr. John Hatfield',
 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
 'Bengtsson, Mr. John Viktor',
 'Calic, Mr. Jovo',
 'Panula, Master. Eino Viljami',
 'Goldsmith, Master. Frank John William "Frankie"',
 'Chibnall, Mrs. (Edith Martha Bowerman)',
 'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
 'Baumann, Mr. John D',
 'Ling, Mr. Lee',
 'Van der hoef, Mr. Wyckoff',
 'Rice, Master. Arthur',
 'Johnson, Miss. Eleanor Ileen',
 'Sivola, Mr. Antti Wilhelm',
 'Smith, Mr. James Clinch',
 'Klasen, Mr. Klas Albin',
 'Lefebre, Master. Henry Forbes',
 'Isham, Miss. Ann Elizabeth',
 'Hale, Mr. Reginald',
 'Leonard, Mr. Lionel',
 'Sage, Miss. Constance Gladys',
 'Pernot, Mr. Rene',
 'Asplund, Master. Clarence Gustaf Hugo',
 'Becker, Master. Richard F',
 'Kink-Heilmann, Miss. Luise Gretchen',
 'Rood, Mr. Hugh Roscoe',
 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)',
 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")',
 'Bourke, Mr. John',
 'Turcin, Mr. Stjepan',
 'Pinsky, Mrs. (Rosa)',
 'Carbines, Mr. William',
 'Andersen-Jensen, Miss. Carla Christine Nielsine',
 'Navratil, Master. Michel M',
 'Brown, Mrs. James Joseph (Margaret Tobin)',
 'Lurette, Miss. Elise',
 'Mernagh, Mr. Robert',
 'Olsen, Mr. Karl Siegwart Andreas',
 'Madigan, Miss. Margaret "Maggie"',
 'Yrois, Miss. Henriette ("Mrs Harbeck")',
 'Vande Walle, Mr. Nestor Cyriel',
 'Sage, Mr. Frederick',
 'Johanson, Mr. Jakob Alfred',
 'Youseff, Mr. Gerious',
 'Cohen, Mr. Gurshon "Gus"',
 'Strom, Miss. Telma Matilda',
 'Backstrom, Mr. Karl Alfred',
 'Albimona, Mr. Nassef Cassem',
 'Carr, Miss. Helen "Ellen"',
 'Blank, Mr. Henry',
 'Ali, Mr. Ahmed',
 'Cameron, Miss. Clear Annie',
 'Perkin, Mr. John Henry',
 'Givard, Mr. Hans Kristensen',
 'Kiernan, Mr. Philip',
 'Newell, Miss. Madeleine',
 'Honkanen, Miss. Eliina',
 'Jacobsohn, Mr. Sidney Samuel',
 'Bazzani, Miss. Albina',
 'Harris, Mr. Walter',
 'Sunderland, Mr. Victor Francis',
 'Bracken, Mr. James H',
 'Green, Mr. George Henry',
 'Nenkoff, Mr. Christo',
 'Hoyt, Mr. Frederick Maxfield',
 'Berglund, Mr. Karl Ivar Sven',
 'Mellors, Mr. William John',
 'Lovell, Mr. John Hall ("Henry")',
 'Fahlstrom, Mr. Arne Jonas',
 'Lefebre, Miss. Mathilde',
 'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
 'Larsson, Mr. Bengt Edvin',
 'Sjostedt, Mr. Ernst Adolf',
 'Asplund, Miss. Lillian Gertrud',
 'Leyson, Mr. Robert William Norman',
 'Harknett, Miss. Alice Phoebe',
 'Hold, Mr. Stephen',
 'Collyer, Miss. Marjorie "Lottie"',
 'Pengelly, Mr. Frederick William',
 'Hunt, Mr. George Henry',
 'Zabour, Miss. Thamine',
 'Murphy, Miss. Katherine "Kate"',
 'Coleridge, Mr. Reginald Charles',
 'Maenpaa, Mr. Matti Alexanteri',
 'Attalah, Mr. Sleiman',
 'Minahan, Dr. William Edward',
 'Lindahl, Miss. Agda Thorilda Viktoria',
 'Hamalainen, Mrs. William (Anna)',
 'Beckwith, Mr. Richard Leonard',
 'Carter, Rev. Ernest Courtenay',
 'Reed, Mr. James George',
 'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
 'Stead, Mr. William Thomas',
 'Lobb, Mr. William Arthur',
 'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
 'Touma, Mrs. Darwis (Hanne Youssef Razi)',
 'Thorne, Mrs. Gertrude Maybelle',
 'Cherry, Miss. Gladys',
 'Ward, Miss. Anna',
 'Parrish, Mrs. (Lutie Davis)',
 'Smith, Mr. Thomas',
 'Asplund, Master. Edvin Rojj Felix',
 'Taussig, Mr. Emil',
 'Harrison, Mr. William',
 'Henry, Miss. Delia',
 'Reeves, Mr. David',
 'Panula, Mr. Ernesti Arvid',
 'Persson, Mr. Ernst Ulrik',
 'Graham, Mrs. William Thompson (Edith Junkins)',
 'Bissette, Miss. Amelia',
 'Cairns, Mr. Alexander',
 'Tornquist, Mr. William Henry',
 'Mellinger, Mrs. (Elizabeth Anne Maidment)',
 'Natsch, Mr. Charles H',
 'Healy, Miss. Hanora "Nora"',
 'Andrews, Miss. Kornelia Theodosia',
 'Lindblom, Miss. Augusta Charlotta',
 'Parkes, Mr. Francis "Frank"',
 'Rice, Master. Eric',
 'Abbott, Mrs. Stanton (Rosa Hunt)',
 'Duane, Mr. Frank',
 'Olsson, Mr. Nils Johan Goransson',
 'de Pelsmaeker, Mr. Alfons',
 'Dorking, Mr. Edward Arthur',
 'Smith, Mr. Richard William',
 'Stankovic, Mr. Ivan',
 'de Mulder, Mr. Theodore',
 'Naidenoff, Mr. Penko',
 'Hosono, Mr. Masabumi',
 'Connolly, Miss. Kate',
 'Barber, Miss. Ellen "Nellie"',
 'Bishop, Mrs. Dickinson H (Helen Walton)',
 'Levy, Mr. Rene Jacques',
 'Haas, Miss. Aloisia',
 'Mineff, Mr. Ivan',
 'Lewy, Mr. Ervin G',
 'Hanna, Mr. Mansour',
 'Allison, Miss. Helen Loraine',
 'Saalfeld, Mr. Adolphe',
 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
 'Kelly, Miss. Anna Katherine "Annie Kate"',
 'McCoy, Mr. Bernard',
 'Johnson, Mr. William Cahoone Jr',
 'Keane, Miss. Nora A',
 'Williams, Mr. Howard Hugh "Harry"',
 'Allison, Master. Hudson Trevor',
 'Fleming, Miss. Margaret',
 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
 'Abelson, Mr. Samuel',
 'Francatelli, Miss. Laura Mabel',
 'Hays, Miss. Margaret Bechstein',
 'Ryerson, Miss. Emily Borie',
 'Lahtinen, Mrs. William (Anna Sylfven)',
 'Hendekovic, Mr. Ignjac',
 'Hart, Mr. Benjamin',
 'Nilsson, Miss. Helmina Josefina',
 'Kantor, Mrs. Sinai (Miriam Sternin)',
 'Moraweck, Dr. Ernest',
 'Wick, Miss. Mary Natalie',
 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
 'Dennis, Mr. Samuel',
 'Danoff, Mr. Yoto',
 'Slayter, Miss. Hilda Mary',
 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
 'Sage, Mr. George John Jr',
 'Young, Miss. Marie Grice',
 'Nysveen, Mr. Johan Hansen',
 'Ball, Mrs. (Ada E Hall)',
 'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
 'Hippach, Miss. Jean Gertrude',
 'McCoy, Miss. Agnes',
 'Partner, Mr. Austen',
 'Graham, Mr. George Edward',
 'Vander Planke, Mr. Leo Edmondus',
 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
 'Denkoff, Mr. Mitto',
 'Pears, Mr. Thomas Clinton',
 'Burns, Miss. Elizabeth Margaret',
 'Dahl, Mr. Karl Edwart',
 'Blackwell, Mr. Stephen Weart',
 'Navratil, Master. Edmond Roger',
 'Fortune, Miss. Alice Elizabeth',
 'Collander, Mr. Erik Gustaf',
 'Sedgwick, Mr. Charles Frederick Waddington',
 'Fox, Mr. Stanley Hubert',
 'Brown, Miss. Amelia "Mildred"',
 'Smith, Miss. Marion Elsie',
 'Davison, Mrs. Thomas Henry (Mary E Finck)',
 'Coutts, Master. William Loch "William"',
 'Dimic, Mr. Jovan',
 'Odahl, Mr. Nils Martin',
 'Williams-Lambert, Mr. Fletcher Fellows',
 'Elias, Mr. Tannous',
 'Arnold-Franchi, Mr. Josef',
 'Yousif, Mr. Wazli',
 'Vanden Steen, Mr. Leo Peter',
 'Bowerman, Miss. Elsie Edith',
 'Funk, Miss. Annie Clemmer',
 'McGovern, Miss. Mary',
 'Mockler, Miss. Helen Mary "Ellie"',
 'Skoog, Mr. Wilhelm',
 'del Carlo, Mr. Sebastiano',
 'Barbara, Mrs. (Catherine David)',
 'Asim, Mr. Adola',
 "O'Brien, Mr. Thomas",
 'Adahl, Mr. Mauritz Nils Martin',
 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
 'Moussa, Mrs. (Mantoura Boulos)',
 'Jermyn, Miss. Annie',
 'Aubart, Mme. Leontine Pauline',
 'Harder, Mr. George Achilles',
 'Wiklund, Mr. Jakob Alfred',
 'Beavan, Mr. William Thomas',
 'Ringhini, Mr. Sante',
 'Palsson, Miss. Stina Viola',
 'Meyer, Mrs. Edgar Joseph (Leila Saks)',
 'Landergren, Miss. Aurora Adelia',
 'Widener, Mr. Harry Elkins',
 'Betros, Mr. Tannous',
 'Gustafsson, Mr. Karl Gideon',
 'Bidois, Miss. Rosalie',
 'Nakid, Miss. Maria ("Mary")',
 'Tikkanen, Mr. Juho',
 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
 'Plotcharsky, Mr. Vasil',
 'Davies, Mr. Charles Henry',
 'Goodwin, Master. Sidney Leonard',
 'Buss, Miss. Kate',
 'Sadlier, Mr. Matthew',
 'Lehmann, Miss. Bertha',
 'Carter, Mr. William Ernest',
 'Jansson, Mr. Carl Olof',
 'Gustafsson, Mr. Johan Birger',
 'Newell, Miss. Marjorie',
 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
 'Johansson, Mr. Erik',
 'Olsson, Miss. Elina',
 'McKane, Mr. Peter David',
 'Pain, Dr. Alfred',
 'Trout, Mrs. William H (Jessie L)',
 'Niskanen, Mr. Juha',
 'Adams, Mr. John',
 'Jussila, Miss. Mari Aina',
 'Hakkarainen, Mr. Pekka Pietari',
 'Oreskovic, Miss. Marija',
 'Gale, Mr. Shadrach',
 'Widegren, Mr. Carl/Charles Peter',
 'Richards, Master. William Rowe',
 'Birkeland, Mr. Hans Martin Monsen',
 'Lefebre, Miss. Ida',
 'Sdycoff, Mr. Todor',
 'Hart, Mr. Henry',
 'Minahan, Miss. Daisy E',
 'Cunningham, Mr. Alfred Fleming',
 'Sundman, Mr. Johan Julian',
 'Meek, Mrs. Thomas (Annie Louise Rowley)',
 'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
 'Silven, Miss. Lyyli Karoliina',
 'Matthews, Mr. William John',
 'Van Impe, Miss. Catharina',
 'Gheorgheff, Mr. Stanio',
 'Charters, Mr. David',
 'Zimmerman, Mr. Leo',
 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
 'Rosblom, Mr. Viktor Richard',
 'Wiseman, Mr. Phillippe',
 'Clarke, Mrs. Charles V (Ada Maria Winfield)',
 'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")',
 'Flynn, Mr. James',
 'Pickard, Mr. Berk (Berk Trembisky)',
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
 'Thorneycroft, Mrs. Percival (Florence Kate White)',
 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
 'Kallio, Mr. Nikolai Erland',
 'Silvey, Mr. William Baird',
 'Carter, Miss. Lucile Polk',
 'Ford, Miss. Doolina Margaret "Daisy"',
 'Richards, Mrs. Sidney (Emily Hocking)',
 'Fortune, Mr. Mark',
 'Kvillner, Mr. Johan Henrik Johannesson',
 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)',
 'Hampe, Mr. Leon',
 'Petterson, Mr. Johan Emil',
 'Reynaldo, Ms. Encarnacion',
 'Johannesen-Bratthammer, Mr. Bernt',
 'Dodge, Master. Washington',
 'Mellinger, Miss. Madeleine Violet',
 'Seward, Mr. Frederic Kimber',
 'Baclini, Miss. Marie Catherine',
 'Peuchen, Major. Arthur Godfrey',
 'West, Mr. Edwy Arthur',
 'Hagland, Mr. Ingvald Olai Olsen',
 'Foreman, Mr. Benjamin Laventall',
 'Goldenberg, Mr. Samuel L',
 'Peduzzi, Mr. Joseph',
 'Jalsevac, Mr. Ivan',
 'Millet, Mr. Francis Davis',
 'Kenyon, Mrs. Frederick R (Marion)',
 'Toomey, Miss. Ellen',
 "O'Connor, Mr. Maurice",
 'Anderson, Mr. Harry',
 'Morley, Mr. William',
 'Gee, Mr. Arthur H',
 'Milling, Mr. Jacob Christian',
 'Maisner, Mr. Simon',
 'Goncalves, Mr. Manuel Estanslas',
 'Campbell, Mr. William',
 'Smart, Mr. John Montgomery',
 'Scanlan, Mr. James',
 'Baclini, Miss. Helene Barbara',
 'Keefe, Mr. Arthur',
 'Cacic, Mr. Luka',
 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
 'Strandberg, Miss. Ida Sofia',
 'Clifford, Mr. George Quincy',
 'Renouf, Mr. Peter Henry',
 'Braund, Mr. Lewis Richard',
 'Karlsson, Mr. Nils August',
 'Hirvonen, Miss. Hildur E',
 'Goodwin, Master. Harold Victor',
 'Frost, Mr. Anthony Wood "Archie"',
 'Rouse, Mr. Richard Henry',
 'Turkula, Mrs. (Hedwig)',
 'Bishop, Mr. Dickinson H',
 'Lefebre, Miss. Jeannie',
 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
 'Kent, Mr. Edward Austin',
 'Somerton, Mr. Francis William',
 'Coutts, Master. Eden Leslie "Neville"',
 'Hagland, Mr. Konrad Mathias Reiersen',
 'Windelov, Mr. Einar',
 'Molson, Mr. Harry Markland',
 'Artagaveytia, Mr. Ramon',
 'Stanley, Mr. Edward Roland',
 'Yousseff, Mr. Gerious',
 'Eustis, Miss. Elizabeth Mussey',
 'Shellard, Mr. Frederick William',
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
 'Svensson, Mr. Olof',
 'Calic, Mr. Petar',
 'Canavan, Miss. Mary',
 "O'Sullivan, Miss. Bridget Mary",
 'Laitinen, Miss. Kristina Sofia',
 'Maioni, Miss. Roberta',
 'Penasco y Castellana, Mr. Victor de Satode',
 'Quick, Mrs. Frederick Charles (Jane Richards)',
 'Bradley, Mr. George ("George Arthur Brayton")',
 'Olsen, Mr. Henry Margido',
 'Lang, Mr. Fang',
 'Daly, Mr. Eugene Patrick',
 'Webber, Mr. James',
 'McGough, Mr. James Robert',
 'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
 'Coleff, Mr. Satio',
 'Walker, Mr. William Anderson',
 'Lemore, Mrs. (Amelia Milley)',
 'Ryan, Mr. Patrick',
 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
 'Pavlovic, Mr. Stefo',
 'Perreault, Miss. Anne',
 'Vovk, Mr. Janko',
 'Lahoud, Mr. Sarkis',
 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
 'Kassem, Mr. Fared',
 'Farrell, Mr. James',
 'Ridsdale, Miss. Lucy',
 'Farthing, Mr. John',
 'Salonen, Mr. Johan Werner',
 'Hocking, Mr. Richard George',
 'Quick, Miss. Phyllis May',
 'Toufik, Mr. Nakli',
 'Elias, Mr. Joseph Jr',
 'Peter, Mrs. Catherine (Catherine Rizk)',
 'Cacic, Miss. Marija',
 'Hart, Miss. Eva Miriam',
 'Butt, Major. Archibald Willingham',
 'LeRoy, Miss. Bertha',
 'Risien, Mr. Samuel Beard',
 'Frolicher, Miss. Hedwig Margaritha',
 'Crosby, Miss. Harriet R',
 'Andersson, Miss. Ingeborg Constanzia',
 'Andersson, Miss. Sigrid Elisabeth',
 'Beane, Mr. Edward',
 'Douglas, Mr. Walter Donald',
 'Nicholson, Mr. Arthur Ernest',
 'Beane, Mrs. Edward (Ethel Clarke)',
 'Padro y Manent, Mr. Julian',
 'Goldsmith, Mr. Frank John',
 'Davies, Master. John Morgan Jr',
 'Thayer, Mr. John Borland Jr',
 'Sharp, Mr. Percival James R',
 "O'Brien, Mr. Timothy",
 'Leeni, Mr. Fahim ("Philip Zenni")',
 'Ohman, Miss. Velin',
 'Wright, Mr. George',
 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
 'Robbins, Mr. Victor',
 'Taussig, Mrs. Emil (Tillie Mandelbaum)',
 'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
 'Morrow, Mr. Thomas Rowan',
 'Sivic, Mr. Husein',
 'Norman, Mr. Robert Douglas',
 'Simmons, Mr. John',
 'Meanwell, Miss. (Marion Ogden)',
 'Davies, Mr. Alfred J',
 'Stoytcheff, Mr. Ilia',
 'Palsson, Mrs. Nils (Alma Cornelia Berglund)',
 'Doharr, Mr. Tannous',
 'Jonsson, Mr. Carl',
 'Harris, Mr. George',
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
 'Flynn, Mr. John Irwin ("Irving")',
 'Kelly, Miss. Mary',
 'Rush, Mr. Alfred George John',
 'Patchett, Mr. George',
 'Garside, Miss. Ethel',
 'Silvey, Mrs. William Baird (Alice Munger)',
 'Caram, Mrs. Joseph (Maria Elias)',
 'Jussila, Mr. Eiriik',
 'Christy, Miss. Julie Rachel',
 'Thayer, Mrs. John Borland (Marian Longstreth Morris)',
 'Downton, Mr. William James',
 'Ross, Mr. John Hugo',
 'Paulner, Mr. Uscher',
 'Taussig, Miss. Ruth',
 'Jarvis, Mr. John Denzil',
 'Frolicher-Stehli, Mr. Maxmillian',
 'Gilinski, Mr. Eliezer',
 'Murdlin, Mr. Joseph',
 'Rintamaki, Mr. Matti',
 'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
 'Elsbury, Mr. William James',
 'Bourke, Miss. Mary',
 'Chapman, Mr. John Henry',
 'Van Impe, Mr. Jean Baptiste',
 'Leitch, Miss. Jessie Wills',
 'Johnson, Mr. Alfred',
 'Boulos, Mr. Hanna',
 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',
 'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)',
 'Slabenoff, Mr. Petco',
 'Harrington, Mr. Charles H',
 'Torber, Mr. Ernst William',
 'Homer, Mr. Harry ("Mr E Haven")',
 'Lindell, Mr. Edvard Bengtsson',
 'Karaic, Mr. Milan',
 'Daniel, Mr. Robert Williams',
 'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)',
 'Shutes, Miss. Elizabeth W',
 'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',
 'Jardin, Mr. Jose Neto',
 'Murphy, Miss. Margaret Jane',
 'Horgan, Mr. John',
 'Brocklebank, Mr. William Alfred',
 'Herman, Miss. Alice',
 'Danbom, Mr. Ernst Gilbert',
 'Lobb, Mrs. William Arthur (Cordelia K Stanlick)',
 'Becker, Miss. Marion Louise',
 'Gavey, Mr. Lawrence',
 'Yasbeck, Mr. Antoni',
 'Kimball, Mr. Edwin Nelson Jr',
 'Nakid, Mr. Sahid',

In [ ]:
revs = []
for name in names:
  if 'Rev.' in name:
    revs.append(name)
print(revs)

['Byles, Rev. Thomas Roussel Davids', 'Bateman, Rev. Robert James', 'Carter, Rev. Ernest Courtenay', 'Kirkland, Rev. Charles Leonard', 'Harper, Rev. John', 'Montvila, Rev. Juozas']

In [ ]:
# for seeing the OTHER inf. about Revs.as df.
df.loc[df['Name'].str.contains('Rev.')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.525,NaN,S
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.000,NaN,S
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.350,NaN,Q
848,849,0,2,"Harper, Rev. John",male,28.0,0,1,248727,33.000,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S

In [ ]:
# To find DF except 'Rev.'.
df.loc[~df['Name'].str.contains('Rev.')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# REGEX Based.
df.loc[(df['Name'].str.contains('Rev\.'))|(df['Name'].str.contains('Mr\.'))]

<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_781/1714151598.py:2: SyntaxWarning: invalid escape sequence '\.'
  df.loc[(df['Name'].str.contains('Rev\.'))|(df['Name'].str.contains('Mr\.'))]
/tmp/ipykernel_781/1714151598.py:2: SyntaxWarning: invalid escape sequence '\.'
  df.loc[(df['Name'].str.contains('Rev\.'))|(df['Name'].str.contains('Mr\.'))]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# REGEX IN SHORT WAY.
df.loc[df['Name'].str.contains('Rev\.|Mr\.', regex=True)]

<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_781/2719307446.py:2: SyntaxWarning: invalid escape sequence '\.'
  df.loc[df['Name'].str.contains('Rev\.|Mr\.', regex=True)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# regex & case.
df.loc[df['Name'].str.contains('Al',case=False|True, regex=True)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.0,4,2,3101281,7.9250,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
833,834,0,3,"Augustsson, Mr. Albert",male,23.0,0,0,347468,7.8542,NaN,S
834,835,0,3,"Allum, Mr. Owen George",male,18.0,0,0,2223,8.3000,NaN,S
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [ ]:
df['Name'] = df['Name'].str.replace('Rev.','Cev',regex=False)
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                 Montvila, Cev Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object